/* This file is generated by the nymea build system. Any changes to this file will
 * be lost.
 *
 * If you want to change this file, edit the plugin's json file.
 */

#ifndef EXTERNPLUGININFO_H
#define EXTERNPLUGININFO_H
#include "typeutils.h"
#include <QLoggingCategory>

// Id definitions
extern PluginId pluginId;
extern VendorId guhVendorId;
extern DeviceClassId simplebuttonDeviceClassId;
extern ActionTypeId simplebuttonPressActionTypeId;
extern EventTypeId simplebuttonPressedEventTypeId;

// Logging category definition
Q_DECLARE_LOGGING_CATEGORY(dcSimpleButton)

#endif // EXTERNPLUGININFO_H
