/* This file is generated by the nymea build system. Any changes to this file will *
 * be lost. If you want to change this file, edit the plugin's json file.          *
 *                                                                                 *
 * NOTE: This file can be included only once per plugin. If you need to access     *
 * definitions from this file in multiple source files, use                        *
 * #include extern-plugininfo.h                                                    *
 * instead and re-run qmake.                                                       */

#ifndef PLUGININFO_H
#define PLUGININFO_H

#include "typeutils.h"

#include <QLoggingCategory>
#include <QObject>

extern "C" const QString libnymea_api_version() { return QString("8.0.0");}

Q_DECLARE_LOGGING_CATEGORY(dcMock)
Q_LOGGING_CATEGORY(dcMock, "Mock")

PluginId pluginId = PluginId("{727a4a9a-c187-446f-aadf-f1b2220607d1}");
ParamTypeId mockPluginConfigParamIntParamTypeId = ParamTypeId("{e1f72121-a426-45e2-b475-8262b5cdf103}");
ParamTypeId mockPluginConfigParamBoolParamTypeId = ParamTypeId("{c75723b6-ea4f-4982-9751-6c5e39c88145}");
VendorId nymeaVendorId = VendorId("{2062d64d-3232-433c-88bc-0d33c0ba2ba6}");
ThingClassId mockThingClassId = ThingClassId("{753f0d32-0468-4d08-82ed-1964aab03298}");
ParamTypeId mockThingHttpportParamTypeId = ParamTypeId("{d4f06047-125e-4479-9810-b54c189917f5}");
ParamTypeId mockThingAsyncParamTypeId = ParamTypeId("{f2977061-4dd0-4ef5-85aa-3b7134743be3}");
ParamTypeId mockThingBrokenParamTypeId = ParamTypeId("{ae8f8901-f2c1-42a5-8111-6d2fc8e4c1e4}");
ParamTypeId mockSettingsSetting1ParamTypeId = ParamTypeId("{367f7ba4-5039-47be-abd8-59cc8eaf4b9a}");
ParamTypeId mockSettingsIntStateWithLimitsMinValueParamTypeId = ParamTypeId("{9c34c881-e825-4f27-bb5c-db868bc60fb1}");
ParamTypeId mockSettingsIntStateWithLimitsMaxValueParamTypeId = ParamTypeId("{984e7ae0-6de7-447e-bc4d-5afde8a00f27}");
ParamTypeId mockDiscoveryResultCountParamTypeId = ParamTypeId("{d222adb4-2f9c-4c3f-8655-76400d0fb6ce}");
StateTypeId mockIntStateTypeId = StateTypeId("{80baec19-54de-4948-ac46-31eabfaceb83}");
StateTypeId mockIntWithLimitsStateTypeId = StateTypeId("{5aa479bd-537a-4716-9852-52f6eec58722}");
StateTypeId mockBoolStateTypeId = StateTypeId("{9dd6a97c-dfd1-43dc-acbd-367932742310}");
StateTypeId mockDoubleStateTypeId = StateTypeId("{7cac53ee-7048-4dc9-b000-7b585390f34c}");
StateTypeId mockBatteryLevelStateTypeId = StateTypeId("{6c8ab9a6-0164-4795-b829-f4394fe4edc4}");
StateTypeId mockBatteryCriticalStateTypeId = StateTypeId("{580bc611-1a55-41f3-996f-8d3ccf543db3}");
StateTypeId mockPowerStateTypeId = StateTypeId("{064aed0d-da4c-49d4-b236-60f97e98ff84}");
StateTypeId mockConnectedStateTypeId = StateTypeId("{9860d105-2bd9-4651-9bc9-13ff4b9039a7}");
StateTypeId mockSignalStrengthStateTypeId = StateTypeId("{2a0213bf-4af3-4384-904e-3376348a597e}");
StateTypeId mockUpdateStatusStateTypeId = StateTypeId("{ebc41327-53d5-40c2-8e7b-1164a8ff359e}");
StateTypeId mockCurrentVersionStateTypeId = StateTypeId("{9f2e1e5d-3f1f-4794-aca3-4e05b7a48842}");
StateTypeId mockAvailableVersionStateTypeId = StateTypeId("{060d7947-2b70-4a2b-b33b-a3577f71faeb}");
EventTypeId mockEvent1EventTypeId = EventTypeId("{45bf3752-0fc6-46b9-89fd-ffd878b5b22b}");
EventTypeId mockEvent2EventTypeId = EventTypeId("{863d5920-b1cf-4eb9-88bd-8f7b8583b1cf}");
ParamTypeId mockEvent2EventIntParamParamTypeId = ParamTypeId("{0550e16d-60b9-4ba5-83f4-4d3cee656121}");
EventTypeId mockPressedEventTypeId = EventTypeId("{f2708625-4b7b-42fd-9a18-3501d89ce599}");
ParamTypeId mockPressedEventButtonNameParamTypeId = ParamTypeId("{5f8adeb2-04f0-4b2e-9dbf-a91966bdcc24}");
ActionTypeId mockIntWithLimitsActionTypeId = ActionTypeId("{5aa479bd-537a-4716-9852-52f6eec58722}");
ParamTypeId mockIntWithLimitsActionIntWithLimitsParamTypeId = ParamTypeId("{5aa479bd-537a-4716-9852-52f6eec58722}");
ActionTypeId mockBatteryLevelActionTypeId = ActionTypeId("{6c8ab9a6-0164-4795-b829-f4394fe4edc4}");
ParamTypeId mockBatteryLevelActionBatteryLevelParamTypeId = ParamTypeId("{6c8ab9a6-0164-4795-b829-f4394fe4edc4}");
ActionTypeId mockPowerActionTypeId = ActionTypeId("{064aed0d-da4c-49d4-b236-60f97e98ff84}");
ParamTypeId mockPowerActionPowerParamTypeId = ParamTypeId("{064aed0d-da4c-49d4-b236-60f97e98ff84}");
ActionTypeId mockSignalStrengthActionTypeId = ActionTypeId("{2a0213bf-4af3-4384-904e-3376348a597e}");
ParamTypeId mockSignalStrengthActionSignalStrengthParamTypeId = ParamTypeId("{2a0213bf-4af3-4384-904e-3376348a597e}");
ActionTypeId mockUpdateStatusActionTypeId = ActionTypeId("{ebc41327-53d5-40c2-8e7b-1164a8ff359e}");
ParamTypeId mockUpdateStatusActionUpdateStatusParamTypeId = ParamTypeId("{ebc41327-53d5-40c2-8e7b-1164a8ff359e}");
ActionTypeId mockWithParamsActionTypeId = ActionTypeId("{dea0f4e1-65e3-4981-8eaa-2701c53a9185}");
ParamTypeId mockWithParamsActionParam1ParamTypeId = ParamTypeId("{a2d3a256-a551-4712-a65b-ecd5a436a1cb}");
ParamTypeId mockWithParamsActionParam2ParamTypeId = ParamTypeId("{304a4899-18be-4e3b-94f4-d03be52f3233}");
ParamTypeId mockWithParamsActionParam3ParamTypeId = ParamTypeId("{d1e428ae-eb8c-45aa-b1b0-e3d7de659c3a}");
ActionTypeId mockWithoutParamsActionTypeId = ActionTypeId("{defd3ed6-1a0d-400b-8879-a0202cf39935}");
ActionTypeId mockAsyncActionTypeId = ActionTypeId("{fbae06d3-7666-483e-a39e-ec50fe89054e}");
ActionTypeId mockFailingActionTypeId = ActionTypeId("{df3cf33d-26d5-4577-9132-9823bd33fad0}");
ActionTypeId mockAsyncFailingActionTypeId = ActionTypeId("{bfe89a1d-3497-4121-8318-e77c37537219}");
ActionTypeId mockPerformUpdateActionTypeId = ActionTypeId("{f2b847dd-ab40-4278-940b-3615f1d7dfd3}");
ActionTypeId mockPressButtonActionTypeId = ActionTypeId("{592dfded-0144-4947-bd02-ca84c2124f39}");
ParamTypeId mockPressButtonActionButtonNameParamTypeId = ParamTypeId("{279e0157-78ea-4bb3-a756-b12fb46cf4fc}");
ActionTypeId mockAddToFavoritesBrowserItemActionTypeId = ActionTypeId("{00b8f0a8-99ca-4aa4-833d-59eb8d4d6de3}");
ActionTypeId mockRemoveFromFavoritesBrowserItemActionTypeId = ActionTypeId("{da6faef8-2816-430e-93bb-57e8f9582d29}");
ThingClassId autoMockThingClassId = ThingClassId("{ab4257b3-7548-47ee-9bd4-7dc3004fd197}");
ParamTypeId autoMockThingHttpportParamTypeId = ParamTypeId("{bfeb0613-dab6-408c-aa27-c362c921d0d1}");
ParamTypeId autoMockThingAsyncParamTypeId = ParamTypeId("{a5c4315f-0624-4971-87c1-4bbfbfdbd16e}");
ParamTypeId autoMockThingBrokenParamTypeId = ParamTypeId("{66179395-ef7a-4013-9fc6-2084104eea09}");
ParamTypeId autoMockSettingsMockSettingParamTypeId = ParamTypeId("{da0b9106-03cf-4631-87e9-26ade3360182}");
StateTypeId autoMockIntStateTypeId = StateTypeId("{74b24296-ba0b-4fbd-87f3-1b09a8bc3e8c}");
StateTypeId autoMockBoolValueStateTypeId = StateTypeId("{978b0ba5-d008-41bd-b63d-a3bd23cb6469}");
EventTypeId autoMockEvent1EventTypeId = EventTypeId("{00f81fca-26f1-4a84-aa2b-4c6a3d953ec6}");
EventTypeId autoMockEvent2EventTypeId = EventTypeId("{6e27922d-aa9d-44d1-b9b4-9faf31b6bd97}");
ParamTypeId autoMockEvent2EventIntParamParamTypeId = ParamTypeId("{12ed5a15-96b4-4381-9d9c-a24875283d4f}");
ActionTypeId autoMockWithParamsActionTypeId = ActionTypeId("{07cd8d5f-2f65-4955-b1f9-05d7f4da488a}");
ParamTypeId autoMockWithParamsActionMockActionParam1ParamTypeId = ParamTypeId("{b8126ba6-3a54-45a3-be4d-63feb0ddb77b}");
ParamTypeId autoMockWithParamsActionMockActionParam2ParamTypeId = ParamTypeId("{df41ba71-e43b-4854-91d1-b19d8066d4f9}");
ActionTypeId autoMockMockActionNoParmsActionTypeId = ActionTypeId("{ef518d53-50e2-4ca5-a4b1-e9a8b9309d44}");
ActionTypeId autoMockMockActionAsyncActionTypeId = ActionTypeId("{5f27a9f2-59cd-4a15-98bd-6ed6e10bc6ed}");
ActionTypeId autoMockMockActionBrokenActionTypeId = ActionTypeId("{58a61de4-472c-4775-8fe8-583a9c83fcf1}");
ActionTypeId autoMockMockActionAsyncBrokenActionTypeId = ActionTypeId("{17ad52dd-ef2f-4947-9b73-5bf6e172a9d0}");
ThingClassId pushButtonMockThingClassId = ThingClassId("{9e03144c-e436-4eea-82d9-ccb33ef778db}");
ParamTypeId pushButtonMockDiscoveryResultCountParamTypeId = ParamTypeId("{c40dbc59-4bba-4871-9b8e-bbd8d5d9193b}");
StateTypeId pushButtonMockColorStateTypeId = StateTypeId("{20dc7c22-c50e-42db-837c-2bbced939f8e}");
StateTypeId pushButtonMockPercentageStateTypeId = StateTypeId("{72981c04-267a-4ba0-a59e-9921d2f3af9c}");
StateTypeId pushButtonMockAllowedValuesStateTypeId = StateTypeId("{05f63f9c-f61e-4dcf-ad55-3f13fde2765b}");
StateTypeId pushButtonMockDoubleStateTypeId = StateTypeId("{53cd7c55-49b7-441b-b970-9048f20f0e2c}");
StateTypeId pushButtonMockBoolStateTypeId = StateTypeId("{e680f7a4-b39e-46da-be41-fa3170fe3768}");
ActionTypeId pushButtonMockColorActionTypeId = ActionTypeId("{20dc7c22-c50e-42db-837c-2bbced939f8e}");
ParamTypeId pushButtonMockColorActionColorParamTypeId = ParamTypeId("{20dc7c22-c50e-42db-837c-2bbced939f8e}");
ActionTypeId pushButtonMockPercentageActionTypeId = ActionTypeId("{72981c04-267a-4ba0-a59e-9921d2f3af9c}");
ParamTypeId pushButtonMockPercentageActionPercentageParamTypeId = ParamTypeId("{72981c04-267a-4ba0-a59e-9921d2f3af9c}");
ActionTypeId pushButtonMockAllowedValuesActionTypeId = ActionTypeId("{05f63f9c-f61e-4dcf-ad55-3f13fde2765b}");
ParamTypeId pushButtonMockAllowedValuesActionAllowedValuesParamTypeId = ParamTypeId("{05f63f9c-f61e-4dcf-ad55-3f13fde2765b}");
ActionTypeId pushButtonMockDoubleActionTypeId = ActionTypeId("{53cd7c55-49b7-441b-b970-9048f20f0e2c}");
ParamTypeId pushButtonMockDoubleActionDoubleParamTypeId = ParamTypeId("{53cd7c55-49b7-441b-b970-9048f20f0e2c}");
ActionTypeId pushButtonMockBoolActionTypeId = ActionTypeId("{e680f7a4-b39e-46da-be41-fa3170fe3768}");
ParamTypeId pushButtonMockBoolActionBoolParamTypeId = ParamTypeId("{e680f7a4-b39e-46da-be41-fa3170fe3768}");
ActionTypeId pushButtonMockTimeoutActionTypeId = ActionTypeId("{54646e7c-bc54-4895-81a2-590d72d120f9}");
ThingClassId displayPinMockThingClassId = ThingClassId("{296f1fd4-e893-46b2-8a42-50d1bceb8730}");
ParamTypeId displayPinMockThingPinParamTypeId = ParamTypeId("{da820e07-22dc-4173-9c07-2f49a4e265f9}");
ParamTypeId displayPinMockDiscoveryResultCountParamTypeId = ParamTypeId("{35f6e4ba-28ad-4152-a58d-ec2600667bcf}");
StateTypeId displayPinMockColorStateTypeId = StateTypeId("{3e161294-8a0d-4384-9676-6959e08cc2fa}");
StateTypeId displayPinMockPercentageStateTypeId = StateTypeId("{527f0687-0b28-4c26-852c-25b8f83e4797}");
StateTypeId displayPinMockAllowedValuesStateTypeId = StateTypeId("{b463c5ae-4d55-402f-8480-a5cdb485c143}");
StateTypeId displayPinMockDoubleStateTypeId = StateTypeId("{17635624-7c19-4bae-8429-2f7aa5d2f843}");
StateTypeId displayPinMockBoolStateTypeId = StateTypeId("{7ffe514f-7999-4998-8350-0e73e222a8c4}");
ActionTypeId displayPinMockColorActionTypeId = ActionTypeId("{3e161294-8a0d-4384-9676-6959e08cc2fa}");
ParamTypeId displayPinMockColorActionColorParamTypeId = ParamTypeId("{3e161294-8a0d-4384-9676-6959e08cc2fa}");
ActionTypeId displayPinMockPercentageActionTypeId = ActionTypeId("{527f0687-0b28-4c26-852c-25b8f83e4797}");
ParamTypeId displayPinMockPercentageActionPercentageParamTypeId = ParamTypeId("{527f0687-0b28-4c26-852c-25b8f83e4797}");
ActionTypeId displayPinMockAllowedValuesActionTypeId = ActionTypeId("{b463c5ae-4d55-402f-8480-a5cdb485c143}");
ParamTypeId displayPinMockAllowedValuesActionAllowedValuesParamTypeId = ParamTypeId("{b463c5ae-4d55-402f-8480-a5cdb485c143}");
ActionTypeId displayPinMockDoubleActionTypeId = ActionTypeId("{17635624-7c19-4bae-8429-2f7aa5d2f843}");
ParamTypeId displayPinMockDoubleActionDoubleParamTypeId = ParamTypeId("{17635624-7c19-4bae-8429-2f7aa5d2f843}");
ActionTypeId displayPinMockBoolActionTypeId = ActionTypeId("{7ffe514f-7999-4998-8350-0e73e222a8c4}");
ParamTypeId displayPinMockBoolActionBoolParamTypeId = ParamTypeId("{7ffe514f-7999-4998-8350-0e73e222a8c4}");
ActionTypeId displayPinMockTimeoutActionTypeId = ActionTypeId("{854a0a4a-803f-4b7f-9dce-b07794f9011b}");
ThingClassId parentMockThingClassId = ThingClassId("{a71fbde9-9a38-4bf8-beab-c8aade2608ba}");
StateTypeId parentMockBoolValueStateTypeId = StateTypeId("{d24ede5f-4064-4898-bb84-cfb533b1fbc0}");
EventTypeId parentMockEvent1EventTypeId = EventTypeId("{61ebadc0-47ea-4800-8c45-ee5222cddb4b}");
ActionTypeId parentMockBoolValueActionTypeId = ActionTypeId("{d24ede5f-4064-4898-bb84-cfb533b1fbc0}");
ParamTypeId parentMockBoolValueActionBoolValueParamTypeId = ParamTypeId("{d24ede5f-4064-4898-bb84-cfb533b1fbc0}");
ThingClassId childMockThingClassId = ThingClassId("{40893c9f-bc47-40c1-8bf7-b390c7c1b4fc}");
StateTypeId childMockBoolValueStateTypeId = StateTypeId("{80ba1449-b485-47d4-a067-6bf306e2a568}");
EventTypeId childMockEvent1EventTypeId = EventTypeId("{dad344b4-fff3-4803-b5cb-7cbb65aa5102}");
ActionTypeId childMockBoolValueActionTypeId = ActionTypeId("{80ba1449-b485-47d4-a067-6bf306e2a568}");
ParamTypeId childMockBoolValueActionBoolValueParamTypeId = ParamTypeId("{80ba1449-b485-47d4-a067-6bf306e2a568}");
ThingClassId inputTypeMockThingClassId = ThingClassId("{515ffdf1-55e5-498d-9abc-4e2fe768f3a9}");
ParamTypeId inputTypeMockThingTextLineParamTypeId = ParamTypeId("{e6acf0c7-4b8e-4296-ac62-855d20deb816}");
ParamTypeId inputTypeMockThingTextAreaParamTypeId = ParamTypeId("{716f0994-bc01-42b0-b64d-59236f7320d2}");
ParamTypeId inputTypeMockThingPasswordParamTypeId = ParamTypeId("{e5c0d14b-c9f1-4aca-a56e-85bfa6977150}");
ParamTypeId inputTypeMockThingSearchParamTypeId = ParamTypeId("{22add8c9-ee4f-43ad-8931-58e999313ac3}");
ParamTypeId inputTypeMockThingMailParamTypeId = ParamTypeId("{a8494faf-3a0f-4cf3-84b7-4b39148a838d}");
ParamTypeId inputTypeMockThingIp4ParamTypeId = ParamTypeId("{9e5f86a0-4bb3-4892-bff8-3fc4032af6e2}");
ParamTypeId inputTypeMockThingIp6ParamTypeId = ParamTypeId("{43bf3832-dd48-4090-a836-656e8b60216e}");
ParamTypeId inputTypeMockThingUrlParamTypeId = ParamTypeId("{fa67229f-fcef-496f-b671-59a4b48f3ab5}");
ParamTypeId inputTypeMockThingMacParamTypeId = ParamTypeId("{e93db587-7919-48f3-8c88-1651de63c765}");
StateTypeId inputTypeMockBoolStateTypeId = StateTypeId("{3bad3a09-5826-4ed7-a832-10e3e2ee2a7d}");
StateTypeId inputTypeMockWritableBoolStateTypeId = StateTypeId("{a7c11774-f31f-4d64-99d1-e0ae5fb35a5c}");
StateTypeId inputTypeMockIntStateTypeId = StateTypeId("{d0fc56ae-5791-4e91-b76c-dadfbc7e7dbb}");
StateTypeId inputTypeMockWritableIntStateTypeId = StateTypeId("{857a8422-983c-47d6-a15f-d8450b3162f7}");
StateTypeId inputTypeMockWritableIntMinMaxStateTypeId = StateTypeId("{86a107bc-510a-4d38-bfeb-0a9c2b6d8d87}");
StateTypeId inputTypeMockUintStateTypeId = StateTypeId("{19e74fcc-bfd5-491f-8eb6-af128e8f1162}");
StateTypeId inputTypeMockWritableUIntStateTypeId = StateTypeId("{563e9c4c-5198-400a-9f6c-358f4752af58}");
StateTypeId inputTypeMockWritableUIntMinMaxStateTypeId = StateTypeId("{79238998-eaab-4d71-b406-5d78f1749751}");
StateTypeId inputTypeMockDoubleStateTypeId = StateTypeId("{f7d2063d-959e-46ac-8568-8b99722d3b22}");
StateTypeId inputTypeMockWritableDoubleStateTypeId = StateTypeId("{8e2eb91b-d60b-4461-9a50-d7b8ad263170}");
StateTypeId inputTypeMockWritableDoubleMinMaxStateTypeId = StateTypeId("{00d3425e-1da6-4748-8906-4555ceefb136}");
StateTypeId inputTypeMockStringStateTypeId = StateTypeId("{27f69ca9-a321-40ff-bfee-4b0272a671b4}");
StateTypeId inputTypeMockWritableStringStateTypeId = StateTypeId("{ef511043-bd1a-4a5f-984c-222b7da43f38}");
StateTypeId inputTypeMockWritableStringSelectionStateTypeId = StateTypeId("{209d7afc-6fe9-4fe9-939b-e472ea0ad639}");
StateTypeId inputTypeMockColorStateTypeId = StateTypeId("{4507d5c6-b692-4bd6-87f2-00364bc0cb4d}");
StateTypeId inputTypeMockWritableColorStateTypeId = StateTypeId("{455f4f68-3cb0-4e8a-a707-62e4a2a8035c}");
StateTypeId inputTypeMockTimeStateTypeId = StateTypeId("{8250c71e-59bc-41ab-b576-99fcfc34e8d1}");
StateTypeId inputTypeMockWritableTimeStateTypeId = StateTypeId("{d64c8b3f-ca7d-47f6-b271-867ffd80a4d4}");
StateTypeId inputTypeMockTimestampIntStateTypeId = StateTypeId("{2c91b5ef-c2d1-4367-bc65-5a13abf69641}");
StateTypeId inputTypeMockWritableTimestampIntStateTypeId = StateTypeId("{88b6746a-b009-4df6-8986-d7884ffd94b2}");
StateTypeId inputTypeMockTimestampUIntStateTypeId = StateTypeId("{6c9a96e8-0d48-4f42-8967-848358fd7f79}");
StateTypeId inputTypeMockWritableTimestampUIntStateTypeId = StateTypeId("{45d0069a-63ac-4265-8170-8152778608ee}");
ActionTypeId inputTypeMockWritableBoolActionTypeId = ActionTypeId("{a7c11774-f31f-4d64-99d1-e0ae5fb35a5c}");
ParamTypeId inputTypeMockWritableBoolActionWritableBoolParamTypeId = ParamTypeId("{a7c11774-f31f-4d64-99d1-e0ae5fb35a5c}");
ActionTypeId inputTypeMockWritableIntActionTypeId = ActionTypeId("{857a8422-983c-47d6-a15f-d8450b3162f7}");
ParamTypeId inputTypeMockWritableIntActionWritableIntParamTypeId = ParamTypeId("{857a8422-983c-47d6-a15f-d8450b3162f7}");
ActionTypeId inputTypeMockWritableIntMinMaxActionTypeId = ActionTypeId("{86a107bc-510a-4d38-bfeb-0a9c2b6d8d87}");
ParamTypeId inputTypeMockWritableIntMinMaxActionWritableIntMinMaxParamTypeId = ParamTypeId("{86a107bc-510a-4d38-bfeb-0a9c2b6d8d87}");
ActionTypeId inputTypeMockWritableUIntActionTypeId = ActionTypeId("{563e9c4c-5198-400a-9f6c-358f4752af58}");
ParamTypeId inputTypeMockWritableUIntActionWritableUIntParamTypeId = ParamTypeId("{563e9c4c-5198-400a-9f6c-358f4752af58}");
ActionTypeId inputTypeMockWritableUIntMinMaxActionTypeId = ActionTypeId("{79238998-eaab-4d71-b406-5d78f1749751}");
ParamTypeId inputTypeMockWritableUIntMinMaxActionWritableUIntMinMaxParamTypeId = ParamTypeId("{79238998-eaab-4d71-b406-5d78f1749751}");
ActionTypeId inputTypeMockWritableDoubleActionTypeId = ActionTypeId("{8e2eb91b-d60b-4461-9a50-d7b8ad263170}");
ParamTypeId inputTypeMockWritableDoubleActionWritableDoubleParamTypeId = ParamTypeId("{8e2eb91b-d60b-4461-9a50-d7b8ad263170}");
ActionTypeId inputTypeMockWritableDoubleMinMaxActionTypeId = ActionTypeId("{00d3425e-1da6-4748-8906-4555ceefb136}");
ParamTypeId inputTypeMockWritableDoubleMinMaxActionWritableDoubleMinMaxParamTypeId = ParamTypeId("{00d3425e-1da6-4748-8906-4555ceefb136}");
ActionTypeId inputTypeMockWritableStringActionTypeId = ActionTypeId("{ef511043-bd1a-4a5f-984c-222b7da43f38}");
ParamTypeId inputTypeMockWritableStringActionWritableStringParamTypeId = ParamTypeId("{ef511043-bd1a-4a5f-984c-222b7da43f38}");
ActionTypeId inputTypeMockWritableStringSelectionActionTypeId = ActionTypeId("{209d7afc-6fe9-4fe9-939b-e472ea0ad639}");
ParamTypeId inputTypeMockWritableStringSelectionActionWritableStringSelectionParamTypeId = ParamTypeId("{209d7afc-6fe9-4fe9-939b-e472ea0ad639}");
ActionTypeId inputTypeMockWritableColorActionTypeId = ActionTypeId("{455f4f68-3cb0-4e8a-a707-62e4a2a8035c}");
ParamTypeId inputTypeMockWritableColorActionWritableColorParamTypeId = ParamTypeId("{455f4f68-3cb0-4e8a-a707-62e4a2a8035c}");
ActionTypeId inputTypeMockWritableTimeActionTypeId = ActionTypeId("{d64c8b3f-ca7d-47f6-b271-867ffd80a4d4}");
ParamTypeId inputTypeMockWritableTimeActionWritableTimeParamTypeId = ParamTypeId("{d64c8b3f-ca7d-47f6-b271-867ffd80a4d4}");
ActionTypeId inputTypeMockWritableTimestampIntActionTypeId = ActionTypeId("{88b6746a-b009-4df6-8986-d7884ffd94b2}");
ParamTypeId inputTypeMockWritableTimestampIntActionWritableTimestampIntParamTypeId = ParamTypeId("{88b6746a-b009-4df6-8986-d7884ffd94b2}");
ActionTypeId inputTypeMockWritableTimestampUIntActionTypeId = ActionTypeId("{45d0069a-63ac-4265-8170-8152778608ee}");
ParamTypeId inputTypeMockWritableTimestampUIntActionWritableTimestampUIntParamTypeId = ParamTypeId("{45d0069a-63ac-4265-8170-8152778608ee}");
ThingClassId oAuthGoogleMockThingClassId = ThingClassId("{805d1692-7bd0-449a-9d5c-43a332ff58f4}");
ThingClassId oAuthSonosMockThingClassId = ThingClassId("{783c615b-7bd6-49a4-98b0-8d1deb3c7156}");
ThingClassId userAndPassMockThingClassId = ThingClassId("{6fe07a77-9c07-4736-81e2-d504314bbcb9}");
ThingClassId genericIoMockThingClassId = ThingClassId("{7cbd729a-465b-4ccb-b59c-5733039dbbed}");
StateTypeId genericIoMockDigitalInput1StateTypeId = StateTypeId("{07165c12-4d53-45c0-8bf1-34618443b706}");
StateTypeId genericIoMockDigitalInput2StateTypeId = StateTypeId("{0a4362ba-a086-4540-84ba-107ef7b99ed8}");
StateTypeId genericIoMockDigitalOutput1StateTypeId = StateTypeId("{d6fcdb52-f7c3-423b-b9f5-1e29f164c42e}");
StateTypeId genericIoMockDigitalOutput2StateTypeId = StateTypeId("{35de8b68-0cf3-4850-a27d-cf9c4a26921f}");
StateTypeId genericIoMockAnalogInput1StateTypeId = StateTypeId("{ac56977c-cbba-47c6-a827-5735d8b0aed6}");
StateTypeId genericIoMockAnalogInput2StateTypeId = StateTypeId("{8e07e57e-ba4e-42df-81ee-5b72ed074532}");
StateTypeId genericIoMockAnalogOutput1StateTypeId = StateTypeId("{70cf053e-4abc-4d88-8e1e-2bd9a62256c7}");
StateTypeId genericIoMockAnalogOutput2StateTypeId = StateTypeId("{e40bcf7d-47b8-41fa-b213-3652a905b376}");
ActionTypeId genericIoMockDigitalOutput1ActionTypeId = ActionTypeId("{d6fcdb52-f7c3-423b-b9f5-1e29f164c42e}");
ParamTypeId genericIoMockDigitalOutput1ActionDigitalOutput1ParamTypeId = ParamTypeId("{d6fcdb52-f7c3-423b-b9f5-1e29f164c42e}");
ActionTypeId genericIoMockDigitalOutput2ActionTypeId = ActionTypeId("{35de8b68-0cf3-4850-a27d-cf9c4a26921f}");
ParamTypeId genericIoMockDigitalOutput2ActionDigitalOutput2ParamTypeId = ParamTypeId("{35de8b68-0cf3-4850-a27d-cf9c4a26921f}");
ActionTypeId genericIoMockAnalogInput1ActionTypeId = ActionTypeId("{ac56977c-cbba-47c6-a827-5735d8b0aed6}");
ParamTypeId genericIoMockAnalogInput1ActionAnalogInput1ParamTypeId = ParamTypeId("{ac56977c-cbba-47c6-a827-5735d8b0aed6}");
ActionTypeId genericIoMockAnalogOutput1ActionTypeId = ActionTypeId("{70cf053e-4abc-4d88-8e1e-2bd9a62256c7}");
ParamTypeId genericIoMockAnalogOutput1ActionAnalogOutput1ParamTypeId = ParamTypeId("{70cf053e-4abc-4d88-8e1e-2bd9a62256c7}");
ActionTypeId genericIoMockAnalogOutput2ActionTypeId = ActionTypeId("{e40bcf7d-47b8-41fa-b213-3652a905b376}");
ParamTypeId genericIoMockAnalogOutput2ActionAnalogOutput2ParamTypeId = ParamTypeId("{e40bcf7d-47b8-41fa-b213-3652a905b376}");
ThingClassId virtualIoLightMockThingClassId = ThingClassId("{98ab137e-757e-43f8-9d9b-5d50d990242a}");
StateTypeId virtualIoLightMockPowerStateTypeId = StateTypeId("{d1917b3d-1530-4cf9-90f7-263ee88e714b}");
ActionTypeId virtualIoLightMockPowerActionTypeId = ActionTypeId("{d1917b3d-1530-4cf9-90f7-263ee88e714b}");
ParamTypeId virtualIoLightMockPowerActionPowerParamTypeId = ParamTypeId("{d1917b3d-1530-4cf9-90f7-263ee88e714b}");
ThingClassId virtualIoTemperatureSensorMockThingClassId = ThingClassId("{f8917e12-c9cb-4ea1-a06e-1ce6db2194f3}");
ParamTypeId virtualIoTemperatureSensorMockSettingsMinTempParamTypeId = ParamTypeId("{803cddbf-94c7-4f35-bc7a-18698b03b942}");
ParamTypeId virtualIoTemperatureSensorMockSettingsMaxTempParamTypeId = ParamTypeId("{7077c56f-c35b-4252-8c15-8fb549be04ce}");
StateTypeId virtualIoTemperatureSensorMockInputStateTypeId = StateTypeId("{fd341f72-6d9a-4812-9f66-47197c48a935}");
StateTypeId virtualIoTemperatureSensorMockTemperatureStateTypeId = StateTypeId("{db9cc518-1012-47e2-8212-6e616fed07a6}");
ActionTypeId virtualIoTemperatureSensorMockInputActionTypeId = ActionTypeId("{fd341f72-6d9a-4812-9f66-47197c48a935}");
ParamTypeId virtualIoTemperatureSensorMockInputActionInputParamTypeId = ParamTypeId("{fd341f72-6d9a-4812-9f66-47197c48a935}");

const QString translations[] {
    //: The name of the Browser Item ActionType ({00b8f0a8-99ca-4aa4-833d-59eb8d4d6de3}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Add to favorites"),

    //: The name of the ParamType (ThingClass: genericIoMock, ActionType: analogInput1, ID: {ac56977c-cbba-47c6-a827-5735d8b0aed6})
    QT_TRANSLATE_NOOP("mock", "Analog Input 1"),

    //: The name of the StateType ({ac56977c-cbba-47c6-a827-5735d8b0aed6}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Analog Input 1"),

    //: The name of the StateType ({8e07e57e-ba4e-42df-81ee-5b72ed074532}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Analog Input 2"),

    //: The name of the ParamType (ThingClass: genericIoMock, ActionType: analogOutput1, ID: {70cf053e-4abc-4d88-8e1e-2bd9a62256c7})
    QT_TRANSLATE_NOOP("mock", "Analog Output 1"),

    //: The name of the StateType ({70cf053e-4abc-4d88-8e1e-2bd9a62256c7}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Analog Output 1"),

    //: The name of the ParamType (ThingClass: genericIoMock, ActionType: analogOutput2, ID: {e40bcf7d-47b8-41fa-b213-3652a905b376})
    QT_TRANSLATE_NOOP("mock", "Analog Output 2"),

    //: The name of the StateType ({e40bcf7d-47b8-41fa-b213-3652a905b376}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Analog Output 2"),

    //: The name of the StateType ({060d7947-2b70-4a2b-b33b-a3577f71faeb}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Available firmware version"),

    //: The name of the ParamType (ThingClass: mock, ActionType: batteryLevel, ID: {6c8ab9a6-0164-4795-b829-f4394fe4edc4})
    QT_TRANSLATE_NOOP("mock", "Battery level"),

    //: The name of the StateType ({6c8ab9a6-0164-4795-b829-f4394fe4edc4}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Battery level"),

    //: The name of the StateType ({3bad3a09-5826-4ed7-a832-10e3e2ee2a7d}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Bool"),

    //: The name of the ParamType (ThingClass: mock, ActionType: pressButton, ID: {279e0157-78ea-4bb3-a756-b12fb46cf4fc})
    QT_TRANSLATE_NOOP("mock", "Button name"),

    //: The name of the ParamType (ThingClass: mock, EventType: pressed, ID: {5f8adeb2-04f0-4b2e-9dbf-a91966bdcc24})
    QT_TRANSLATE_NOOP("mock", "Button name"),

    //: The name of the EventType ({f2708625-4b7b-42fd-9a18-3501d89ce599}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Button pressed"),

    //: The name of the StateType ({4507d5c6-b692-4bd6-87f2-00364bc0cb4d}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Color"),

    //: The name of the StateType ({9860d105-2bd9-4651-9bc9-13ff4b9039a7}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Connected"),

    //: The name of the ParamType (ThingClass: genericIoMock, ActionType: digitalOutput1, ID: {d6fcdb52-f7c3-423b-b9f5-1e29f164c42e})
    QT_TRANSLATE_NOOP("mock", "Digital Output 1"),

    //: The name of the StateType ({d6fcdb52-f7c3-423b-b9f5-1e29f164c42e}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Digital Output 1"),

    //: The name of the ParamType (ThingClass: genericIoMock, ActionType: digitalOutput2, ID: {35de8b68-0cf3-4850-a27d-cf9c4a26921f})
    QT_TRANSLATE_NOOP("mock", "Digital Output 2"),

    //: The name of the StateType ({35de8b68-0cf3-4850-a27d-cf9c4a26921f}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Digital Output 2"),

    //: The name of the StateType ({07165c12-4d53-45c0-8bf1-34618443b706}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Digital input 1"),

    //: The name of the StateType ({0a4362ba-a086-4540-84ba-107ef7b99ed8}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Digital input 2"),

    //: The name of the StateType ({f7d2063d-959e-46ac-8568-8b99722d3b22}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Double"),

    //: The name of the StateType ({978b0ba5-d008-41bd-b63d-a3bd23cb6469}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Dummy bool state"),

    //: The name of the StateType ({9dd6a97c-dfd1-43dc-acbd-367932742310}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Dummy bool state"),

    //: The name of the StateType ({7cac53ee-7048-4dc9-b000-7b585390f34c}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Dummy double state"),

    //: The name of the StateType ({74b24296-ba0b-4fbd-87f3-1b09a8bc3e8c}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Dummy int state"),

    //: The name of the StateType ({80baec19-54de-4948-ac46-31eabfaceb83}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Dummy int state"),

    //: The name of the ParamType (ThingClass: mock, ActionType: intWithLimits, ID: {5aa479bd-537a-4716-9852-52f6eec58722})
    QT_TRANSLATE_NOOP("mock", "Dummy int state with limits"),

    //: The name of the StateType ({5aa479bd-537a-4716-9852-52f6eec58722}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Dummy int state with limits"),

    //: The name of the EventType ({dad344b4-fff3-4803-b5cb-7cbb65aa5102}) of ThingClass childMock
    QT_TRANSLATE_NOOP("mock", "Event 1"),

    //: The name of the EventType ({61ebadc0-47ea-4800-8c45-ee5222cddb4b}) of ThingClass parentMock
    QT_TRANSLATE_NOOP("mock", "Event 1"),

    //: The name of the StateType ({9f2e1e5d-3f1f-4794-aca3-4e05b7a48842}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Firmware version"),

    //: The name of the ThingClass ({7cbd729a-465b-4ccb-b59c-5733039dbbed})
    QT_TRANSLATE_NOOP("mock", "Generic IO pins"),

    //: The name of the ThingClass ({98ab137e-757e-43f8-9d9b-5d50d990242a})
    QT_TRANSLATE_NOOP("mock", "Generic Light (Mock)"),

    //: The name of the ThingClass ({f8917e12-c9cb-4ea1-a06e-1ce6db2194f3})
    QT_TRANSLATE_NOOP("mock", "Generic Temperature Sensor (Mock)"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {9e5f86a0-4bb3-4892-bff8-3fc4032af6e2})
    QT_TRANSLATE_NOOP("mock", "IPv4 address"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {43bf3832-dd48-4090-a836-656e8b60216e})
    QT_TRANSLATE_NOOP("mock", "IPv6 address"),

    //: The name of the ParamType (ThingClass: virtualIoTemperatureSensorMock, ActionType: input, ID: {fd341f72-6d9a-4812-9f66-47197c48a935})
    QT_TRANSLATE_NOOP("mock", "Input"),

    //: The name of the StateType ({fd341f72-6d9a-4812-9f66-47197c48a935}) of ThingClass virtualIoTemperatureSensorMock
    QT_TRANSLATE_NOOP("mock", "Input"),

    //: The name of the StateType ({d0fc56ae-5791-4e91-b76c-dadfbc7e7dbb}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Int"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {e93db587-7919-48f3-8c88-1651de63c765})
    QT_TRANSLATE_NOOP("mock", "Mac address"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {a8494faf-3a0f-4cf3-84b7-4b39148a838d})
    QT_TRANSLATE_NOOP("mock", "Mail address"),

    //: The name of the ParamType (ThingClass: virtualIoTemperatureSensorMock, Type: settings, ID: {7077c56f-c35b-4252-8c15-8fb549be04ce})
    QT_TRANSLATE_NOOP("mock", "Maximum temperature"),

    //: The name of the ParamType (ThingClass: mock, Type: settings, ID: {984e7ae0-6de7-447e-bc4d-5afde8a00f27})
    QT_TRANSLATE_NOOP("mock", "Maximum value for int with limits"),

    //: The name of the ParamType (ThingClass: virtualIoTemperatureSensorMock, Type: settings, ID: {803cddbf-94c7-4f35-bc7a-18698b03b942})
    QT_TRANSLATE_NOOP("mock", "Minimum temperature"),

    //: The name of the ParamType (ThingClass: mock, Type: settings, ID: {9c34c881-e825-4f27-bb5c-db868bc60fb1})
    QT_TRANSLATE_NOOP("mock", "Minimum value for int with limits"),

    //: The name of the ActionType ({07cd8d5f-2f65-4955-b1f9-05d7f4da488a}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Mock Action 1 (with params)"),

    //: The name of the ActionType ({dea0f4e1-65e3-4981-8eaa-2701c53a9185}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Mock Action 1 (with params)"),

    //: The name of the ActionType ({ef518d53-50e2-4ca5-a4b1-e9a8b9309d44}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Mock Action 2 (without params)"),

    //: The name of the ActionType ({defd3ed6-1a0d-400b-8879-a0202cf39935}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Mock Action 2 (without params)"),

    //: The name of the ActionType ({5f27a9f2-59cd-4a15-98bd-6ed6e10bc6ed}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Mock Action 3 (async)"),

    //: The name of the ActionType ({fbae06d3-7666-483e-a39e-ec50fe89054e}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Mock Action 3 (async)"),

    //: The name of the ActionType ({58a61de4-472c-4775-8fe8-583a9c83fcf1}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Mock Action 4 (broken)"),

    //: The name of the ActionType ({df3cf33d-26d5-4577-9132-9823bd33fad0}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Mock Action 4 (broken)"),

    //: The name of the ActionType ({17ad52dd-ef2f-4947-9b73-5bf6e172a9d0}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Mock Action 5 (async, broken)"),

    //: The name of the ActionType ({bfe89a1d-3497-4121-8318-e77c37537219}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Mock Action 5 (async, broken)"),

    //: The name of the EventType ({00f81fca-26f1-4a84-aa2b-4c6a3d953ec6}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Mock Event 1"),

    //: The name of the EventType ({45bf3752-0fc6-46b9-89fd-ffd878b5b22b}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Mock Event 1"),

    //: The name of the EventType ({6e27922d-aa9d-44d1-b9b4-9faf31b6bd97}) of ThingClass autoMock
    QT_TRANSLATE_NOOP("mock", "Mock Event 2"),

    //: The name of the EventType ({863d5920-b1cf-4eb9-88bd-8f7b8583b1cf}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Mock Event 2"),

    //: The name of the ThingClass ({753f0d32-0468-4d08-82ed-1964aab03298})
    QT_TRANSLATE_NOOP("mock", "Mock Thing"),

    //: The name of the ParamType (ThingClass: autoMock, Type: settings, ID: {da0b9106-03cf-4631-87e9-26ade3360182})
    QT_TRANSLATE_NOOP("mock", "Mock setting"),

    //: The name of the ThingClass ({ab4257b3-7548-47ee-9bd4-7dc3004fd197})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (Auto created)"),

    //: The name of the ThingClass ({40893c9f-bc47-40c1-8bf7-b390c7c1b4fc})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (Child)"),

    //: The name of the ThingClass ({296f1fd4-e893-46b2-8a42-50d1bceb8730})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (Display Pin)"),

    //: The name of the ThingClass ({805d1692-7bd0-449a-9d5c-43a332ff58f4})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (Google OAuth)"),

    //: The name of the ThingClass ({515ffdf1-55e5-498d-9abc-4e2fe768f3a9})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (InputTypes)"),

    //: The name of the ThingClass ({a71fbde9-9a38-4bf8-beab-c8aade2608ba})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (Parent)"),

    //: The name of the ThingClass ({9e03144c-e436-4eea-82d9-ccb33ef778db})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (Push Button)"),

    //: The name of the ThingClass ({783c615b-7bd6-49a4-98b0-8d1deb3c7156})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (Sonos OAuth)"),

    //: The name of the ThingClass ({6fe07a77-9c07-4736-81e2-d504314bbcb9})
    QT_TRANSLATE_NOOP("mock", "Mocked Thing (User & Password)"),

    //: The name of the plugin mock ({727a4a9a-c187-446f-aadf-f1b2220607d1})
    QT_TRANSLATE_NOOP("mock", "Mocked things"),

    //: The name of the ParamType (ThingClass: mock, ActionType: withParams, ID: {d1e428ae-eb8c-45aa-b1b0-e3d7de659c3a})
    QT_TRANSLATE_NOOP("mock", "Param with default value"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {e5c0d14b-c9f1-4aca-a56e-85bfa6977150})
    QT_TRANSLATE_NOOP("mock", "Password text"),

    //: The name of the ParamType (ThingClass: virtualIoLightMock, ActionType: power, ID: {d1917b3d-1530-4cf9-90f7-263ee88e714b})
    QT_TRANSLATE_NOOP("mock", "Power"),

    //: The name of the StateType ({d1917b3d-1530-4cf9-90f7-263ee88e714b}) of ThingClass virtualIoLightMock
    QT_TRANSLATE_NOOP("mock", "Power"),

    //: The name of the ActionType ({592dfded-0144-4947-bd02-ca84c2124f39}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Press button"),

    //: The name of the Browser Item ActionType ({da6faef8-2816-430e-93bb-57e8f9582d29}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Remove from favorites"),

    //: The name of the ParamType (ThingClass: mock, Type: discovery, ID: {d222adb4-2f9c-4c3f-8655-76400d0fb6ce})
    QT_TRANSLATE_NOOP("mock", "Result count"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {22add8c9-ee4f-43ad-8931-58e999313ac3})
    QT_TRANSLATE_NOOP("mock", "Search text"),

    //: The name of the ActionType ({d6fcdb52-f7c3-423b-b9f5-1e29f164c42e}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Set Digital Output 1"),

    //: The name of the ActionType ({35de8b68-0cf3-4850-a27d-cf9c4a26921f}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Set Digital Output 2"),

    //: The name of the ActionType ({70cf053e-4abc-4d88-8e1e-2bd9a62256c7}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Set Output Input 1"),

    //: The name of the ActionType ({e40bcf7d-47b8-41fa-b213-3652a905b376}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Set Output Input 2"),

    //: The name of the ActionType ({a7c11774-f31f-4d64-99d1-e0ae5fb35a5c}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Bool"),

    //: The name of the ActionType ({455f4f68-3cb0-4e8a-a707-62e4a2a8035c}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Color"),

    //: The name of the ActionType ({8e2eb91b-d60b-4461-9a50-d7b8ad263170}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Double"),

    //: The name of the ActionType ({00d3425e-1da6-4748-8906-4555ceefb136}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Double (min/max)"),

    //: The name of the ActionType ({857a8422-983c-47d6-a15f-d8450b3162f7}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Int"),

    //: The name of the ActionType ({86a107bc-510a-4d38-bfeb-0a9c2b6d8d87}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Int (min/max)"),

    //: The name of the ActionType ({ef511043-bd1a-4a5f-984c-222b7da43f38}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable String"),

    //: The name of the ActionType ({209d7afc-6fe9-4fe9-939b-e472ea0ad639}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable String (selection)"),

    //: The name of the ActionType ({d64c8b3f-ca7d-47f6-b271-867ffd80a4d4}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Time"),

    //: The name of the ActionType ({88b6746a-b009-4df6-8986-d7884ffd94b2}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Timestamp (Int)"),

    //: The name of the ActionType ({45d0069a-63ac-4265-8170-8152778608ee}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable Timestamp (UInt)"),

    //: The name of the ActionType ({563e9c4c-5198-400a-9f6c-358f4752af58}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable UInt"),

    //: The name of the ActionType ({79238998-eaab-4d71-b406-5d78f1749751}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Set Writable UInt (min/max)"),

    //: The name of the ActionType ({b463c5ae-4d55-402f-8480-a5cdb485c143}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "Set allowed values"),

    //: The name of the ActionType ({05f63f9c-f61e-4dcf-ad55-3f13fde2765b}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "Set allowed values"),

    //: The name of the ActionType ({ac56977c-cbba-47c6-a827-5735d8b0aed6}) of ThingClass genericIoMock
    QT_TRANSLATE_NOOP("mock", "Set analog input 1"),

    //: The name of the ActionType ({6c8ab9a6-0164-4795-b829-f4394fe4edc4}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Set battery level"),

    //: The name of the ActionType ({80ba1449-b485-47d4-a067-6bf306e2a568}) of ThingClass childMock
    QT_TRANSLATE_NOOP("mock", "Set bool value"),

    //: The name of the ActionType ({d24ede5f-4064-4898-bb84-cfb533b1fbc0}) of ThingClass parentMock
    QT_TRANSLATE_NOOP("mock", "Set bool value"),

    //: The name of the ActionType ({7ffe514f-7999-4998-8350-0e73e222a8c4}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "Set bool value"),

    //: The name of the ActionType ({e680f7a4-b39e-46da-be41-fa3170fe3768}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "Set bool value"),

    //: The name of the ActionType ({3e161294-8a0d-4384-9676-6959e08cc2fa}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "Set color"),

    //: The name of the ActionType ({20dc7c22-c50e-42db-837c-2bbced939f8e}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "Set color"),

    //: The name of the ActionType ({17635624-7c19-4bae-8429-2f7aa5d2f843}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "Set double value"),

    //: The name of the ActionType ({53cd7c55-49b7-441b-b970-9048f20f0e2c}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "Set double value"),

    //: The name of the ActionType ({5aa479bd-537a-4716-9852-52f6eec58722}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Set dummy int state with limits"),

    //: The name of the ActionType ({fd341f72-6d9a-4812-9f66-47197c48a935}) of ThingClass virtualIoTemperatureSensorMock
    QT_TRANSLATE_NOOP("mock", "Set input"),

    //: The name of the ActionType ({527f0687-0b28-4c26-852c-25b8f83e4797}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "Set percentage"),

    //: The name of the ActionType ({72981c04-267a-4ba0-a59e-9921d2f3af9c}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "Set percentage"),

    //: The name of the ActionType ({d1917b3d-1530-4cf9-90f7-263ee88e714b}) of ThingClass virtualIoLightMock
    QT_TRANSLATE_NOOP("mock", "Set power"),

    //: The name of the ActionType ({2a0213bf-4af3-4384-904e-3376348a597e}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Set signal strength"),

    //: The name of the ActionType ({ebc41327-53d5-40c2-8e7b-1164a8ff359e}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Set update status"),

    //: The name of the ParamType (ThingClass: mock, Type: settings, ID: {367f7ba4-5039-47be-abd8-59cc8eaf4b9a})
    QT_TRANSLATE_NOOP("mock", "Setting 1"),

    //: The name of the ParamType (ThingClass: mock, ActionType: signalStrength, ID: {2a0213bf-4af3-4384-904e-3376348a597e})
    QT_TRANSLATE_NOOP("mock", "Signal strength"),

    //: The name of the StateType ({2a0213bf-4af3-4384-904e-3376348a597e}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Signal strength"),

    //: The name of the StateType ({27f69ca9-a321-40ff-bfee-4b0272a671b4}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "String"),

    //: The name of the StateType ({db9cc518-1012-47e2-8212-6e616fed07a6}) of ThingClass virtualIoTemperatureSensorMock
    QT_TRANSLATE_NOOP("mock", "Temperature"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {716f0994-bc01-42b0-b64d-59236f7320d2})
    QT_TRANSLATE_NOOP("mock", "Text area"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {e6acf0c7-4b8e-4296-ac62-855d20deb816})
    QT_TRANSLATE_NOOP("mock", "Text line"),

    //: The name of the StateType ({8250c71e-59bc-41ab-b576-99fcfc34e8d1}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Time"),

    //: The name of the ActionType ({854a0a4a-803f-4b7f-9dce-b07794f9011b}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "Timeout action"),

    //: The name of the ActionType ({54646e7c-bc54-4895-81a2-590d72d120f9}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "Timeout action"),

    //: The name of the StateType ({2c91b5ef-c2d1-4367-bc65-5a13abf69641}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Timestamp (Int)"),

    //: The name of the StateType ({6c9a96e8-0d48-4f42-8967-848358fd7f79}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Timestamp (UInt)"),

    //: The name of the StateType ({19e74fcc-bfd5-491f-8eb6-af128e8f1162}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "UInt"),

    //: The name of the ParamType (ThingClass: inputTypeMock, Type: thing, ID: {fa67229f-fcef-496f-b671-59a4b48f3ab5})
    QT_TRANSLATE_NOOP("mock", "URL"),

    //: The name of the ActionType ({f2b847dd-ab40-4278-940b-3615f1d7dfd3}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Update firmware"),

    //: The name of the ParamType (ThingClass: mock, ActionType: updateStatus, ID: {ebc41327-53d5-40c2-8e7b-1164a8ff359e})
    QT_TRANSLATE_NOOP("mock", "Update status"),

    //: The name of the StateType ({ebc41327-53d5-40c2-8e7b-1164a8ff359e}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "Update status"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableBool, ID: {a7c11774-f31f-4d64-99d1-e0ae5fb35a5c})
    QT_TRANSLATE_NOOP("mock", "Writable Bool"),

    //: The name of the StateType ({a7c11774-f31f-4d64-99d1-e0ae5fb35a5c}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Bool"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableColor, ID: {455f4f68-3cb0-4e8a-a707-62e4a2a8035c})
    QT_TRANSLATE_NOOP("mock", "Writable Color"),

    //: The name of the StateType ({455f4f68-3cb0-4e8a-a707-62e4a2a8035c}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Color"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableDouble, ID: {8e2eb91b-d60b-4461-9a50-d7b8ad263170})
    QT_TRANSLATE_NOOP("mock", "Writable Double"),

    //: The name of the StateType ({8e2eb91b-d60b-4461-9a50-d7b8ad263170}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Double"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableDoubleMinMax, ID: {00d3425e-1da6-4748-8906-4555ceefb136})
    QT_TRANSLATE_NOOP("mock", "Writable Double (min/max)"),

    //: The name of the StateType ({00d3425e-1da6-4748-8906-4555ceefb136}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Double (min/max)"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableInt, ID: {857a8422-983c-47d6-a15f-d8450b3162f7})
    QT_TRANSLATE_NOOP("mock", "Writable Int"),

    //: The name of the StateType ({857a8422-983c-47d6-a15f-d8450b3162f7}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Int"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableIntMinMax, ID: {86a107bc-510a-4d38-bfeb-0a9c2b6d8d87})
    QT_TRANSLATE_NOOP("mock", "Writable Int (min/max)"),

    //: The name of the StateType ({86a107bc-510a-4d38-bfeb-0a9c2b6d8d87}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Int (min/max)"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableString, ID: {ef511043-bd1a-4a5f-984c-222b7da43f38})
    QT_TRANSLATE_NOOP("mock", "Writable String"),

    //: The name of the StateType ({ef511043-bd1a-4a5f-984c-222b7da43f38}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable String"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableStringSelection, ID: {209d7afc-6fe9-4fe9-939b-e472ea0ad639})
    QT_TRANSLATE_NOOP("mock", "Writable String (selection)"),

    //: The name of the StateType ({209d7afc-6fe9-4fe9-939b-e472ea0ad639}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable String (selection)"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableTime, ID: {d64c8b3f-ca7d-47f6-b271-867ffd80a4d4})
    QT_TRANSLATE_NOOP("mock", "Writable Time"),

    //: The name of the StateType ({d64c8b3f-ca7d-47f6-b271-867ffd80a4d4}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Time"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableTimestampInt, ID: {88b6746a-b009-4df6-8986-d7884ffd94b2})
    QT_TRANSLATE_NOOP("mock", "Writable Timestamp (Int)"),

    //: The name of the StateType ({88b6746a-b009-4df6-8986-d7884ffd94b2}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Timestamp (Int)"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableTimestampUInt, ID: {45d0069a-63ac-4265-8170-8152778608ee})
    QT_TRANSLATE_NOOP("mock", "Writable Timestamp (UInt)"),

    //: The name of the StateType ({45d0069a-63ac-4265-8170-8152778608ee}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable Timestamp (UInt)"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableUInt, ID: {563e9c4c-5198-400a-9f6c-358f4752af58})
    QT_TRANSLATE_NOOP("mock", "Writable UInt"),

    //: The name of the StateType ({563e9c4c-5198-400a-9f6c-358f4752af58}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable UInt"),

    //: The name of the ParamType (ThingClass: inputTypeMock, ActionType: writableUIntMinMax, ID: {79238998-eaab-4d71-b406-5d78f1749751})
    QT_TRANSLATE_NOOP("mock", "Writable UInt (min/max)"),

    //: The name of the StateType ({79238998-eaab-4d71-b406-5d78f1749751}) of ThingClass inputTypeMock
    QT_TRANSLATE_NOOP("mock", "Writable UInt (min/max)"),

    //: The name of the ParamType (ThingClass: displayPinMock, ActionType: allowedValues, ID: {b463c5ae-4d55-402f-8480-a5cdb485c143})
    QT_TRANSLATE_NOOP("mock", "allowed values"),

    //: The name of the StateType ({b463c5ae-4d55-402f-8480-a5cdb485c143}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "allowed values"),

    //: The name of the ParamType (ThingClass: pushButtonMock, ActionType: allowedValues, ID: {05f63f9c-f61e-4dcf-ad55-3f13fde2765b})
    QT_TRANSLATE_NOOP("mock", "allowed values"),

    //: The name of the StateType ({05f63f9c-f61e-4dcf-ad55-3f13fde2765b}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "allowed values"),

    //: The name of the ParamType (ThingClass: autoMock, Type: thing, ID: {a5c4315f-0624-4971-87c1-4bbfbfdbd16e})
    QT_TRANSLATE_NOOP("mock", "async"),

    //: The name of the ParamType (ThingClass: mock, Type: thing, ID: {f2977061-4dd0-4ef5-85aa-3b7134743be3})
    QT_TRANSLATE_NOOP("mock", "async"),

    //: The name of the StateType ({580bc611-1a55-41f3-996f-8d3ccf543db3}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "battery level critical"),

    //: The name of the ParamType (ThingClass: childMock, ActionType: boolValue, ID: {80ba1449-b485-47d4-a067-6bf306e2a568})
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the StateType ({80ba1449-b485-47d4-a067-6bf306e2a568}) of ThingClass childMock
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the ParamType (ThingClass: parentMock, ActionType: boolValue, ID: {d24ede5f-4064-4898-bb84-cfb533b1fbc0})
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the StateType ({d24ede5f-4064-4898-bb84-cfb533b1fbc0}) of ThingClass parentMock
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the ParamType (ThingClass: displayPinMock, ActionType: bool, ID: {7ffe514f-7999-4998-8350-0e73e222a8c4})
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the StateType ({7ffe514f-7999-4998-8350-0e73e222a8c4}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the ParamType (ThingClass: pushButtonMock, ActionType: bool, ID: {e680f7a4-b39e-46da-be41-fa3170fe3768})
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the StateType ({e680f7a4-b39e-46da-be41-fa3170fe3768}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "bool value"),

    //: The name of the ParamType (ThingClass: autoMock, Type: thing, ID: {66179395-ef7a-4013-9fc6-2084104eea09})
    QT_TRANSLATE_NOOP("mock", "broken"),

    //: The name of the ParamType (ThingClass: mock, Type: thing, ID: {ae8f8901-f2c1-42a5-8111-6d2fc8e4c1e4})
    QT_TRANSLATE_NOOP("mock", "broken"),

    //: The name of the ParamType (ThingClass: displayPinMock, ActionType: color, ID: {3e161294-8a0d-4384-9676-6959e08cc2fa})
    QT_TRANSLATE_NOOP("mock", "color"),

    //: The name of the StateType ({3e161294-8a0d-4384-9676-6959e08cc2fa}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "color"),

    //: The name of the ParamType (ThingClass: pushButtonMock, ActionType: color, ID: {20dc7c22-c50e-42db-837c-2bbced939f8e})
    QT_TRANSLATE_NOOP("mock", "color"),

    //: The name of the StateType ({20dc7c22-c50e-42db-837c-2bbced939f8e}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "color"),

    //: The name of the ParamType (ThingClass: mock, Type: plugin, ID: {c75723b6-ea4f-4982-9751-6c5e39c88145})
    QT_TRANSLATE_NOOP("mock", "configParamBool"),

    //: The name of the ParamType (ThingClass: mock, Type: plugin, ID: {e1f72121-a426-45e2-b475-8262b5cdf103})
    QT_TRANSLATE_NOOP("mock", "configParamInt"),

    //: The name of the ParamType (ThingClass: displayPinMock, ActionType: double, ID: {17635624-7c19-4bae-8429-2f7aa5d2f843})
    QT_TRANSLATE_NOOP("mock", "double value"),

    //: The name of the StateType ({17635624-7c19-4bae-8429-2f7aa5d2f843}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "double value"),

    //: The name of the ParamType (ThingClass: pushButtonMock, ActionType: double, ID: {53cd7c55-49b7-441b-b970-9048f20f0e2c})
    QT_TRANSLATE_NOOP("mock", "double value"),

    //: The name of the StateType ({53cd7c55-49b7-441b-b970-9048f20f0e2c}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "double value"),

    //: The name of the ParamType (ThingClass: autoMock, Type: thing, ID: {bfeb0613-dab6-408c-aa27-c362c921d0d1})
    QT_TRANSLATE_NOOP("mock", "http port"),

    //: The name of the ParamType (ThingClass: mock, Type: thing, ID: {d4f06047-125e-4479-9810-b54c189917f5})
    QT_TRANSLATE_NOOP("mock", "http port"),

    //: The name of the ParamType (ThingClass: autoMock, ActionType: withParams, ID: {b8126ba6-3a54-45a3-be4d-63feb0ddb77b})
    QT_TRANSLATE_NOOP("mock", "mockActionParam1"),

    //: The name of the ParamType (ThingClass: mock, ActionType: withParams, ID: {a2d3a256-a551-4712-a65b-ecd5a436a1cb})
    QT_TRANSLATE_NOOP("mock", "mockActionParam1"),

    //: The name of the ParamType (ThingClass: autoMock, ActionType: withParams, ID: {df41ba71-e43b-4854-91d1-b19d8066d4f9})
    QT_TRANSLATE_NOOP("mock", "mockActionParam2"),

    //: The name of the ParamType (ThingClass: mock, ActionType: withParams, ID: {304a4899-18be-4e3b-94f4-d03be52f3233})
    QT_TRANSLATE_NOOP("mock", "mockActionParam2"),

    //: The name of the ParamType (ThingClass: autoMock, EventType: event2, ID: {12ed5a15-96b4-4381-9d9c-a24875283d4f})
    QT_TRANSLATE_NOOP("mock", "mockParamInt"),

    //: The name of the ParamType (ThingClass: mock, EventType: event2, ID: {0550e16d-60b9-4ba5-83f4-4d3cee656121})
    QT_TRANSLATE_NOOP("mock", "mockParamInt"),

    //: The name of the vendor ({2062d64d-3232-433c-88bc-0d33c0ba2ba6})
    QT_TRANSLATE_NOOP("mock", "nymea"),

    //: The name of the ParamType (ThingClass: displayPinMock, ActionType: percentage, ID: {527f0687-0b28-4c26-852c-25b8f83e4797})
    QT_TRANSLATE_NOOP("mock", "percentage"),

    //: The name of the StateType ({527f0687-0b28-4c26-852c-25b8f83e4797}) of ThingClass displayPinMock
    QT_TRANSLATE_NOOP("mock", "percentage"),

    //: The name of the ParamType (ThingClass: pushButtonMock, ActionType: percentage, ID: {72981c04-267a-4ba0-a59e-9921d2f3af9c})
    QT_TRANSLATE_NOOP("mock", "percentage"),

    //: The name of the StateType ({72981c04-267a-4ba0-a59e-9921d2f3af9c}) of ThingClass pushButtonMock
    QT_TRANSLATE_NOOP("mock", "percentage"),

    //: The name of the ParamType (ThingClass: displayPinMock, Type: thing, ID: {da820e07-22dc-4173-9c07-2f49a4e265f9})
    QT_TRANSLATE_NOOP("mock", "pin"),

    //: The name of the ParamType (ThingClass: mock, ActionType: power, ID: {064aed0d-da4c-49d4-b236-60f97e98ff84})
    QT_TRANSLATE_NOOP("mock", "powered"),

    //: The name of the StateType ({064aed0d-da4c-49d4-b236-60f97e98ff84}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "powered"),

    //: The name of the ParamType (ThingClass: displayPinMock, Type: discovery, ID: {35f6e4ba-28ad-4152-a58d-ec2600667bcf})
    QT_TRANSLATE_NOOP("mock", "resultCount"),

    //: The name of the ParamType (ThingClass: pushButtonMock, Type: discovery, ID: {c40dbc59-4bba-4871-9b8e-bbd8d5d9193b})
    QT_TRANSLATE_NOOP("mock", "resultCount"),

    //: The name of the ActionType ({064aed0d-da4c-49d4-b236-60f97e98ff84}) of ThingClass mock
    QT_TRANSLATE_NOOP("mock", "set power")
};

#endif // PLUGININFO_H
