# icons for the webserver
RESOURCES += $$top_srcdir/icons.qrc

HEADERS += $$top_srcdir/server/guhcore.h \
    $$top_srcdir/server/tcpserver.h \
    $$top_srcdir/server/ruleengine.h \
    $$top_srcdir/server/rule.h \
    $$top_srcdir/server/stateevaluator.h \
    $$top_srcdir/server/webserver.h \
    $$top_srcdir/server/transportinterface.h \
    $$top_srcdir/server/servermanager.h \
    $$top_srcdir/server/httprequest.h \
    $$top_srcdir/server/websocketserver.h \
    $$top_srcdir/server/httpreply.h \
    $$top_srcdir/server/guhconfiguration.h \
    $$top_srcdir/server/bluetoothserver.h \
    $$top_srcdir/server/jsonrpc/jsonrpcserver.h \
    $$top_srcdir/server/jsonrpc/jsonhandler.h \
    $$top_srcdir/server/jsonrpc/devicehandler.h \
    $$top_srcdir/server/jsonrpc/jsontypes.h \
    $$top_srcdir/server/jsonrpc/ruleshandler.h \
    $$top_srcdir/server/jsonrpc/actionhandler.h \
    $$top_srcdir/server/jsonrpc/eventhandler.h \
    $$top_srcdir/server/jsonrpc/statehandler.h \
    $$top_srcdir/server/jsonrpc/logginghandler.h \
    $$top_srcdir/server/jsonrpc/configurationhandler.h \
    $$top_srcdir/server/jsonrpc/networkmanagerhandler.h \
    $$top_srcdir/server/logging/logging.h \
    $$top_srcdir/server/logging/logengine.h \
    $$top_srcdir/server/logging/logfilter.h \
    $$top_srcdir/server/logging/logentry.h \
    $$top_srcdir/server/rest/restserver.h \
    $$top_srcdir/server/rest/restresource.h \
    $$top_srcdir/server/rest/devicesresource.h \
    $$top_srcdir/server/rest/deviceclassesresource.h \
    $$top_srcdir/server/rest/vendorsresource.h \
    $$top_srcdir/server/rest/logsresource.h \
    $$top_srcdir/server/rest/pluginsresource.h \
    $$top_srcdir/server/rest/rulesresource.h \
    $$top_srcdir/server/time/timedescriptor.h \
    $$top_srcdir/server/time/calendaritem.h \
    $$top_srcdir/server/time/repeatingoption.h \
    $$top_srcdir/server/time/timeeventitem.h \
    $$top_srcdir/server/time/timemanager.h \
    $$top_srcdir/server/networkmanager/dbus-interfaces.h \
    $$top_srcdir/server/networkmanager/networkmanager.h \
    $$top_srcdir/server/networkmanager/networkdevice.h \
    $$top_srcdir/server/networkmanager/wirelessaccesspoint.h \
    $$top_srcdir/server/networkmanager/wirelessnetworkdevice.h \
    $$top_srcdir/server/networkmanager/networksettings.h \
    $$top_srcdir/server/networkmanager/networkconnection.h \
    $$top_srcdir/server/networkmanager/wirednetworkdevice.h \
    $$top_srcdir/server/usermanager.h \


SOURCES += $$top_srcdir/server/guhcore.cpp \
    $$top_srcdir/server/tcpserver.cpp \
    $$top_srcdir/server/ruleengine.cpp \
    $$top_srcdir/server/rule.cpp \
    $$top_srcdir/server/stateevaluator.cpp \
    $$top_srcdir/server/webserver.cpp \
    $$top_srcdir/server/transportinterface.cpp \
    $$top_srcdir/server/servermanager.cpp \
    $$top_srcdir/server/httprequest.cpp \
    $$top_srcdir/server/websocketserver.cpp \
    $$top_srcdir/server/httpreply.cpp \
    $$top_srcdir/server/guhconfiguration.cpp \
    $$top_srcdir/server/bluetoothserver.cpp \
    $$top_srcdir/server/jsonrpc/jsonrpcserver.cpp \
    $$top_srcdir/server/jsonrpc/jsonhandler.cpp \
    $$top_srcdir/server/jsonrpc/devicehandler.cpp \
    $$top_srcdir/server/jsonrpc/jsontypes.cpp \
    $$top_srcdir/server/jsonrpc/ruleshandler.cpp \
    $$top_srcdir/server/jsonrpc/actionhandler.cpp \
    $$top_srcdir/server/jsonrpc/eventhandler.cpp \
    $$top_srcdir/server/jsonrpc/statehandler.cpp \
    $$top_srcdir/server/jsonrpc/logginghandler.cpp \
    $$top_srcdir/server/jsonrpc/configurationhandler.cpp \
    $$top_srcdir/server/jsonrpc/networkmanagerhandler.cpp \
    $$top_srcdir/server/logging/logengine.cpp \
    $$top_srcdir/server/logging/logfilter.cpp \
    $$top_srcdir/server/logging/logentry.cpp \
    $$top_srcdir/server/rest/restserver.cpp \
    $$top_srcdir/server/rest/restresource.cpp \
    $$top_srcdir/server/rest/devicesresource.cpp \
    $$top_srcdir/server/rest/deviceclassesresource.cpp \
    $$top_srcdir/server/rest/vendorsresource.cpp \
    $$top_srcdir/server/rest/logsresource.cpp \
    $$top_srcdir/server/rest/pluginsresource.cpp \
    $$top_srcdir/server/rest/rulesresource.cpp \
    $$top_srcdir/server/time/timedescriptor.cpp \
    $$top_srcdir/server/time/calendaritem.cpp \
    $$top_srcdir/server/time/repeatingoption.cpp \
    $$top_srcdir/server/time/timeeventitem.cpp \
    $$top_srcdir/server/time/timemanager.cpp \
    $$top_srcdir/server/networkmanager/networkmanager.cpp \
    $$top_srcdir/server/networkmanager/networkdevice.cpp \
    $$top_srcdir/server/networkmanager/wirelessaccesspoint.cpp \
    $$top_srcdir/server/networkmanager/wirelessnetworkdevice.cpp \
    $$top_srcdir/server/networkmanager/networksettings.cpp \
    $$top_srcdir/server/networkmanager/networkconnection.cpp \
    $$top_srcdir/server/networkmanager/wirednetworkdevice.cpp \
    $$top_srcdir/server/usermanager.cpp \

